import { Payment } from "@/app/payments/columns";

export const columnsData: Payment[] = [
  {
    id: "728ed52f",
    amount: 100,
    status: "pending",
    email: "m@example.com",
  },
  {
    id: "3a7b9e14",
    amount: 200,
    status: "processing",
    email: "n@example.com",
  },
  {
    id: "c5f1b2a7",
    amount: 150,
    status: "pending",
    email: "o@example.com",
  },
  {
    id: "e2d5f4c1",
    amount: 75,
    status: "failed",
    email: "p@example.com",
  },
  {
    id: "9b8a7c6d",
    amount: 300,
    status: "processing",
    email: "q@example.com",
  },
  {
    id: "5e6f8a2b",
    amount: 50,
    status: "pending",
    email: "r@example.com",
  },
  {
    id: "1c2e3d4f",
    amount: 80,
    status: "pending",
    email: "s@example.com",
  },
  {
    id: "7a8b9c1d",
    amount: 250,
    status: "processing",
    email: "t@example.com",
  },
  {
    id: "3e4f5d6c",
    amount: 120,
    status: "failed",
    email: "u@example.com",
  },
  {
    id: "9c7b8a5e",
    amount: 180,
    status: "pending",
    email: "v@example.com",
  },
  {
    id: "2d3f4e5c",
    amount: 90,
    status: "processing",
    email: "w@example.com",
  },
  {
    id: "6a7b9c2d",
    amount: 60,
    status: "pending",
    email: "x@example.com",
  },
  {
    id: "8d9e1f2c",
    amount: 210,
    status: "failed",
    email: "y@example.com",
  },
  {
    id: "4a5c6b8d",
    amount: 175,
    status: "pending",
    email: "z@example.com",
  },
  {
    id: "1e3d2f4c",
    amount: 130,
    status: "processing",
    email: "aa@example.com",
  },
  {
    id: "9b8c7e5f",
    amount: 220,
    status: "pending",
    email: "bb@example.com",
  },
  {
    id: "6d7f8c9e",
    amount: 70,
    status: "failed",
    email: "cc@example.com",
  },
  {
    id: "3b5c6e9d",
    amount: 190,
    status: "processing",
    email: "dd@example.com",
  },
  {
    id: "1f3e4d6c",
    amount: 100,
    status: "pending",
    email: "ee@example.com",
  },
  {
    id: "7b8d9c5f",
    amount: 260,
    status: "processing",
    email: "ff@example.com",
  },
  {
    id: "4e6d8f9b",
    amount: 40,
    status: "failed",
    email: "gg@example.com",
  },
  {
    id: "2c3e5f4b",
    amount: 160,
    status: "pending",
    email: "hh@example.com",
  },
  {
    id: "7d9e1c2f",
    amount: 280,
    status: "processing",
    email: "ii@example.com",
  },
  {
    id: "5a6c7b8d",
    amount: 55,
    status: "pending",
    email: "jj@example.com",
  },
  {
    id: "2e3f5d7c",
    amount: 230,
    status: "failed",
    email: "kk@example.com",
  },
  {
    id: "9c8b7e4f",
    amount: 140,
    status: "pending",
    email: "ll@example.com",
  },
  {
    id: "6d7f8a2e",
    amount: 95,
    status: "processing",
    email: "mm@example.com",
  },
  {
    id: "4b5c7d9e",
    amount: 270,
    status: "pending",
    email: "nn@example.com",
  },
  {
    id: "1e3f5c6d",
    amount: 85,
    status: "failed",
    email: "oo@example.com",
  },
  {
    id: "8a9c6e7f",
    amount: 200,
    status: "processing",
    email: "pp@example.com",
  },
  {
    id: "4d6f8a9c",
    amount: 45,
    status: "pending",
    email: "qq@example.com",
  },
  {
    id: "2b3c4e6f",
    amount: 180,
    status: "failed",
    email: "rr@example.com",
  },
  {
    id: "7d9e1c3f",
    amount: 120,
    status: "pending",
    email: "ss@example.com",
  },
  {
    id: "5a6c7d9e",
    amount: 240,
    status: "processing",
    email: "tt@example.com",
  },
  {
    id: "3b4d6e8f",
    amount: 65,
    status: "pending",
    email: "uu@example.com",
  },
  {
    id: "1e2f3d5c",
    amount: 135,
    status: "failed",
    email: "vv@example.com",
  },
  {
    id: "7a8b9d6e",
    amount: 290,
    status: "pending",
    email: "ww@example.com",
  },
  {
    id: "4c5d7e8f",
    amount: 75,
    status: "processing",
    email: "xx@example.com",
  },
  {
    id: "2b3d5e6f",
    amount: 210,
    status: "pending",
    email: "yy@example.com",
  },
  {
    id: "8a9c1d3e",
    amount: 125,
    status: "failed",
    email: "zz@example.com",
  },
  {
    id: "4b6d8e9f",
    amount: 260,
    status: "processing",
    email: "aaa@example.com",
  },
  {
    id: "2c4d5f6e",
    amount: 55,
    status: "pending",
    email: "bbb@example.com",
  },
  {
    id: "7a8c9d2e",
    amount: 280,
    status: "failed",
    email: "ccc@example.com",
  },
  {
    id: "5b6d8f9c",
    amount: 150,
    status: "pending",
    email: "ddd@example.com",
  },
  {
    id: "3e4f6d8a",
    amount: 100,
    status: "processing",
    email: "eee@example.com",
  },
  {
    id: "9c1d2e4f",
    amount: 230,
    status: "pending",
    email: "fff@example.com",
  },
  {
    id: "5b7d8f9e",
    amount: 60,
    status: "failed",
    email: "ggg@example.com",
  },
  {
    id: "2c3e5d7f",
    amount: 190,
    status: "processing",
    email: "hhh@example.com",
  },
  {
    id: "8a9c2e3f",
    amount: 135,
    status: "pending",
    email: "iii@example.com",
  },
  {
    id: "4d5f6e8c",
    amount: 220,
    status: "failed",
    email: "jjj@example.com",
  },
  {
    id: "1e3d5f6c",
    amount: 70,
    status: "processing",
    email: "kkk@example.com",
  },
  {
    id: "7a9c1e3f",
    amount: 250,
    status: "pending",
    email: "lll@example.com",
  },
  {
    id: "4d6e7f8c",
    amount: 95,
    status: "failed",
    email: "mmm@example.com",
  },
  {
    id: "2b4c6d9e",
    amount: 175,
    status: "pending",
    email: "nnn@example.com",
  },
  {
    id: "8a9c2e4f",
    amount: 130,
    status: "processing",
    email: "ooo@example.com",
  },
  {
    id: "5d6f7c8e",
    amount: 220,
    status: "pending",
    email: "ppp@example.com",
  },
  {
    id: "3b4d6e9f",
    amount: 80,
    status: "failed",
    email: "qqq@example.com",
  },
  {
    id: "1c2e3f5d",
    amount: 240,
    status: "processing",
    email: "rrr@example.com",
  },
  {
    id: "8a9b7c8e",
    amount: 65,
    status: "pending",
    email: "sss@example.com",
  },
  {
    id: "3d4f6c7e",
    amount: 145,
    status: "failed",
    email: "ttt@example.com",
  },
  {
    id: "1b2c4e6f",
    amount: 290,
    status: "pending",
    email: "uuu@example.com",
  },
  {
    id: "7a9c5e6f",
    amount: 45,
    status: "processing",
    email: "vvv@example.com",
  },
  {
    id: "3c4e6f7d",
    amount: 200,
    status: "pending",
    email: "www@example.com",
  },
  {
    id: "1a3c5e8f",
    amount: 125,
    status: "failed",
    email: "xxx@example.com",
  },
  {
    id: "6b7d8e9f",
    amount: 260,
    status: "processing",
    email: "yyy@example.com",
  },
  {
    id: "4c5e7f9d",
    amount: 50,
    status: "pending",
    email: "zzz@example.com",
  },
];
